# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniar < Formula
  desc "uniar is UNI'S ON AIR music and scene cards database and manage your scene cards collection tool."
  homepage "https://github.com/litencatt/uniar"
  version "0.14.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/litencatt/uniar/releases/download/v0.14.0/uniar_v0.14.0_darwin_arm64.zip"
      sha256 "3c00436b3e05bc38c14794c9c8ebad246cb75dde4b84917f34f79da9765e6ed5"

      def install
        bin.install "uniar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/litencatt/uniar/releases/download/v0.14.0/uniar_v0.14.0_darwin_amd64.zip"
      sha256 "9f26ce2f483cd6d02b2c0e32546de05a749d10e87545baedcc2ecfaf1da4ecc6"

      def install
        bin.install "uniar"
      end
    end
  end
end
