# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniar < Formula
  desc "uniar is UNI'S ON AIR music and scene cards database and manage your scene cards collection tool."
  homepage "https://github.com/litencatt/uniar"
  version "0.13.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/litencatt/uniar/releases/download/v0.13.0/uniar_v0.13.0_darwin_arm64.zip"
      sha256 "dbf2ce69c60d8abe555a4993111c7f18aaff8030597f95ce3928b3724f36bb8a"

      def install
        bin.install "uniar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/litencatt/uniar/releases/download/v0.13.0/uniar_v0.13.0_darwin_amd64.zip"
      sha256 "b8d0111b329590918a165a1d31cb32841e537e8b4b568ea38cffc8c9f1fbca3a"

      def install
        bin.install "uniar"
      end
    end
  end
end
