# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniar < Formula
  desc "uniar is UNI'S ON AIR music and scene cards database and manage your scene cards collection tool."
  homepage "https://github.com/litencatt/uniar"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/litencatt/uniar/releases/download/v0.2.0/uniar_v0.2.0_darwin_amd64.zip"
    sha256 "216592650b5c608be6385fdb960ecdf6d40bcd07dafcd30455149f4ec2c09d7b"

    def install
      bin.install "uniar"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Uniar
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
